name: Build and Push Docker Image

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u crimsongabriel --password-stdin
            - name: Build and push Docker image
              run: |
                docker build . --tag ghcr.io/crimsongabriel/chmurkadocker:latest
                docker push ghcr.io/crimsongabriel/chmurkadocker:latest
            - name: Make package public
              run: |
                gh api --method PATCH -H "Accept: application/vnd.github.v3+json" \
                /user/packages/container/chmurkadocker/visibility \
                -f visibility='public' \
                -H "Authorization: token ${{ secrets.TOKEN }}"
